### ISSUE TITLE
Neither ctrl nor shift works in category filters

### ISSUE THREAD

**Issue by srhb** [SupesSolutions/RWAutoSeller#3] opened 2019-04-20 21:08 UTC
I'm not sure how to debug this. I'm guessing the mod does something slightly strange to figure out whether these keys are being held, since they both work just fine in every other aspect of the game.

**Comment by srhb** [comment] 2019-04-20 21:08
Oh, this is on Linux, fwiw.

**Comment by SupesSolutions** [comment] 2019-04-21 05:38
I just need to check you're using the modifier keys in the right place as the category tree isn't affected by modifier keys, but the def listbox to the top right of it should use them

holding shift+click while dragging should select those being dragged over, where holding ctrl and clicking individual items lets you select all those items.  let me know if this isn't the case.

**Comment by srhb** [comment] 2019-04-21 06:17
Sure! Yes, we're talking about the upper right hand list. Here's the behaviour:

Left-clicking item bar while item foo is selected clears item foo and selects item bar.
ctrl+left click on item bar while item foo is selects clears item foo and selects item bar.
shift+left click on item bar while item foo is selected clears item foo and selects item bar.
Dragging from (left button down) foo to (left button up) bar selects all items from foo to bar inclusive.
Shift+dragging appears to do the same thing.

As far as I can surmise, it's always behaving as if I did not hold any modifier.

**Comment by SupesSolutions** [comment] 2019-04-21 16:22
I made an update to the experimental branch regarding shift modifier.

Ctrl behaviour is working as intended on my end, so it might be a linux thing.

to elaborate on Ctrl (since my earlier description of Ctrl might not have been very clear), it acts as a toggle on clicked row without clearing other rows, Ctrl+drag acts as concatenate dragged rows with currently selected rows.

**Comment by SupesSolutions** [comment] 2019-04-24 17:14
going to close this, since if input events are being intercepted before unity can process them by my widgets, either intercepted by another mod or the OS, then there's nothing I can really do.

**Closed as completed by SupesSolutions** 2019-04-24 17:14 UTC

**Comment by srhb** [comment] 2019-05-13 12:56
In case anyone else hits this, here's some information I managed to dig up that helps work around the issue:

https://github.com/FluffierThanThou/WorkTab/issues/82

It's still not clear to me what causes this (since ctrl click works fine for eg. the increment job buttons) but I can confirm that the ctrl+alt+lmb workaround does work for me
