### ISSUE TITLE
Filters don't see all my animals

### ISSUE THREAD

**Issue by meiskam** [SupesSolutions/RWAutoSeller#5] opened 2020-03-17 02:42 UTC
I've created a rule to filter race donkey, tested and gotten a list of a few of them, but actually have more than that.  Screenshot album to show what I mean: https://imgur.com/a/N5pz9tV

The issue persists after reloads, here is my save file: https://easyupload.io/cq93v2

Is there a max animal count I've gone over and it just doesn't process more than that?

Note: I did have other mods in the save before, but removed them all and the issue persisted

**Comment by SupesSolutions** [comment] 2020-03-17 21:39
some rows get merged into one row for similar aged/value/gender as to not produce a huge list

Donkey 14 row likely has Donkey 15 and Donkey 16 and so on under it's unbrella as they are are very similar.  so it's not a bug

**Closed as completed by SupesSolutions** 2020-03-17 21:39 UTC
Labels: wontfix

**Comment by meiskam** [comment] 2020-03-17 22:33
it'd be nice to have some kind of visual cue that this is happening, even if it's just a `+` at the end of the name to show more have collapsed
